name: lint

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    lint:
        name: Lint

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: 8.1
                extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

            - name: Install dependencies
              run: composer install --no-interaction --no-suggest --ignore-platform-reqs

            - name: Run phpcs
              run: ./vendor/bin/duster phpcs --ignore=*/public/index.php

            - name: Tlint Lint
              run: ./vendor/bin/duster tlint
