name: lint

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    duster:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: tighten/duster-action@v1

